CREATE TABLE delivery(
no BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
status ENUM('PENDING','COMPLETE') NOT NULL,
manager VARCHAR(60) NULL,
FOREIGN KEY (manager) REFERENCES manager(id),
img TEXT NULL,
comment TEXT NULL,
completed_at TIMESTAMP NULL)
