CREATE TABLE product(
no BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(60) NOT NULL,
purchase_price INT UNSIGNED NOT NULL,
sale_price INT UNSIGNED NOT NULL,
stock INT UNSIGNED UNSIGNED NOT NULL,
size TEXT)