CREATE TABLE salelog(
no BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
customer BIGINT NULL,
FOREIGN KEY (customer) REFERENCES customer(no),
delivery BIGINT NULL,
FOREIGN KEY (delivery) REFERENCES delivery(no),
sale_price INT UNSIGNED NOT NULL,
manager VARCHAR(60) NOT NULL,
FOREIGN KEY (manager) REFERENCES manager(id),
quantity INT UNSIGNED NOT NULL,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
